 {
    "comp_output": "Traceback (most recent call last):\n  File \"main.py\", line 1, in <module>\n    import tensorflow as tf\nModuleNotFoundError: No module named 'tensorflow'\nError in sys.excepthook:\nTraceback (most recent call last):\n  File \"/usr/lib/python3/dist-packages/apport_python_hook.py\", line 63, in apport_excepthook\n    from apport.fileutils import likely_packaged, get_recent_crashes\n  File \"/usr/lib/python3/dist-packages/apport/__init__.py\", line 5, in <module>\n    from apport.report import Report\n  File \"/usr/lib/python3/dist-packages/apport/report.py\", line 30, in <module>\n    import apport.fileutils\n  File \"/usr/lib/python3/dist-packages/apport/fileutils.py\", line 23, in <module>\n    from apport.packaging_impl import impl as packaging\n  File \"/usr/lib/python3/dist-packages/apport/packaging_impl.py\", line 24, in <module>\n    import apt\n  File \"/usr/lib/python3/dist-packages/apt/__init__.py\", line 23, in <module>\n    import apt_pkg\nModuleNotFoundError: No module named 'apt_pkg'\nOriginal exception was:\nTraceback (most recent call last):\n  File \"main.py\", line 1, in <module>\n    import tensorflow as tf\nModuleNotFoundError: No module named 'tensorflow'",
    "content": "import tensorflow as tf\n",
    "language": "python"
  }